#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            // Vanilla
            "a3_air_f",
            "a3_air_f_beta",
            "a3_air_f_beta_heli_attack_01",
            "a3_air_f_beta_heli_attack_02",
            "a3_air_f_beta_heli_transport_01",
            "a3_air_f_beta_heli_transport_02",
            "a3_air_f_beta_parachute_01",
            "a3_air_f_beta_parachute_02",
            "a3_air_f_epb_heli_light_03",
            "a3_air_f_epc_plane_cas_01",
            "a3_air_f_epc_plane_cas_02",
            "a3_air_f_epc_plane_fighter_03",
            "a3_air_f_gamma_plane_fighter_03",
            "a3_air_f_gamma_uav_01",
            "a3_air_f_gamma_uav_02",
            "a3_air_f_heli",
            "a3_air_f_heli_heli_attack_01",
            "a3_air_f_heli_heli_attack_02",
            "a3_air_f_heli_heli_light_01",
            "a3_air_f_heli_heli_light_02",
            "a3_air_f_heli_heli_light_03",
            "a3_air_f_heli_heli_transport_01",
            "a3_air_f_heli_heli_transport_02",
            "a3_air_f_heli_heli_transport_03",
            "a3_air_f_heli_heli_transport_04",
            "a3_air_f_heli_light_01",
            "a3_air_f_heli_light_02",
            "a3_armor_f",
            "a3_armor_f_amv",
            "a3_armor_f_apc_wheeled_03",
            "a3_armor_f_beta",
            "a3_armor_f_beta_apc_tracked_02",
            "a3_armor_f_epb_apc_tracked_03",
            "a3_armor_f_epb_mbt_03",
            "a3_armor_f_epc_mbt_01",
            "a3_armor_f_marid",
            "a3_armor_f_panther",
            "a3_armor_f_slammer",
            "a3_armor_f_t100k",
            "a3_boat_f",
            "a3_boat_f_beta_boat_armed_01",
            "a3_boat_f_beta_boat_transport_01",
            "a3_boat_f_boat_armed_01",
            "a3_boat_f_boat_transport_01",
            "a3_boat_f_civilian_boat",
            "a3_boat_f_epc_submarine_01_f",
            "a3_boat_f_gamma_boat_transport_01",
            "a3_boat_f_heli_boat_armed_01",
            "a3_boat_f_heli_sdv_01",
            "a3_boat_f_sdv_01",
            "a3_boat_f_trawler",
            "a3_cargoposes_f",
            "a3_cargoposes_f_heli",
            "a3_characters_f",
            "a3_characters_f_beta",
            "a3_characters_f_blufor",
            "a3_characters_f_bootcamp",
            "a3_characters_f_bootcamp_common",
            "a3_characters_f_civil",
            "a3_characters_f_common",
            "a3_characters_f_epa",
            "a3_characters_f_epb",
            "a3_characters_f_epb_heads",
            "a3_characters_f_epc",
            "a3_characters_f_gamma",
            "a3_characters_f_heads",
            "a3_characters_f_indep",
            "a3_characters_f_kart",
            "a3_characters_f_mark",
            "a3_characters_f_opfor",
            "a3_characters_f_proxies",
            "a3_data_f",
            "a3_data_f_bootcamp",
            "a3_data_f_curator",
            "a3_data_f_curator_characters",
            "a3_data_f_curator_eagle",
            "a3_data_f_curator_intel",
            "a3_data_f_curator_misc",
            "a3_data_f_curator_respawn",
            "a3_data_f_curator_virtual",
            "a3_data_f_exp_a",
            "a3_data_f_exp_a_virtual",
            "a3_data_f_exp_b",
            "a3_data_f_heli",
            "a3_data_f_hook",
            "a3_data_f_kart",
            "a3_data_f_kart_particleeffects",
            "a3_data_f_mark",
            "a3_data_f_particleeffects",
            "a3_dubbing_radio_f",
            "a3_editor_f",
            "a3_soft_f",
            "a3_soft_f_beta_quadbike",
            "a3_soft_f_bootcamp_offroad_01",
            "a3_soft_f_bootcamp_quadbike",
            "a3_soft_f_bootcamp_truck",
            "a3_soft_f_car",
            "a3_soft_f_crusher_ugv",
            "a3_soft_f_epc_truck_03",
            "a3_soft_f_gamma_hemtt",
            "a3_soft_f_gamma_offroad",
            "a3_soft_f_gamma_quadbike",
            "a3_soft_f_gamma_truckheavy",
            "a3_soft_f_heli_car",
            "a3_soft_f_heli_crusher_ugv",
            "a3_soft_f_heli_mrap_01",
            "a3_soft_f_heli_mrap_02",
            "a3_soft_f_heli_mrap_03",
            "a3_soft_f_heli_quadbike",
            "a3_soft_f_heli_suv",
            "a3_soft_f_heli_truck",
            "a3_soft_f_hemtt",
            "a3_soft_f_kart_kart_01",
            "a3_soft_f_mrap_01",
            "a3_soft_f_mrap_02",
            "a3_soft_f_mrap_03",
            "a3_soft_f_offroad_01",
            "a3_soft_f_quadbike",
            "a3_soft_f_suv",
            "a3_soft_f_truck",
            "a3_soft_f_truckheavy",
            "a3_static_f",
            "a3_static_f_beta_mortar_01",
            "a3_static_f_gamma",
            "a3_static_f_gamma_aa",
            "a3_static_f_gamma_at",
            "a3_static_f_gamma_mortar_01",
            "a3_static_f_mark_designator_01",
            "a3_static_f_mark_designator_02",
            "a3_static_f_mortar_01",
            "a3_supplies_f_heli",
            "a3_supplies_f_heli_bladders",
            "a3_supplies_f_heli_cargonets",
            "a3_supplies_f_heli_fuel",
            "a3_supplies_f_heli_slingload",
            "a3_supplies_f_mark",
            "a3_uav_f_characters_f_gamma",
            "a3_uav_f_weapons_f_gamma_ammoboxes",
            "a3_weapons_f",
            "a3_weapons_f_aaf",
            "a3_weapons_f_acc",
            "a3_weapons_f_ammoboxes",
            "a3_weapons_f_beta",
            "a3_weapons_f_beta_acc",
            "a3_weapons_f_beta_ammoboxes",
            "a3_weapons_f_beta_ebr",
            "a3_weapons_f_beta_rifles_khaybar",
            "a3_weapons_f_beta_rifles_mx",
            "a3_weapons_f_beta_rifles_trg20",
            "a3_weapons_f_bootcamp",
            "a3_weapons_f_bootcamp_ammoboxes",
            "a3_weapons_f_bootcamp_longrangerifles_gm6",
            "a3_weapons_f_bootcamp_longrangerifles_m320",
            "a3_weapons_f_csat",
            "a3_weapons_f_dummyweapons",
            "a3_weapons_f_ebr",
            "a3_weapons_f_epa",
            "a3_weapons_f_epa_acc",
            "a3_weapons_f_epa_ammoboxes",
            "a3_weapons_f_epa_ebr",
            "a3_weapons_f_epa_longrangerifles_dmr_01",
            "a3_weapons_f_epa_longrangerifles_gm6",
            "a3_weapons_f_epa_rifles_mx",
            "a3_weapons_f_epb",
            "a3_weapons_f_epb_acc",
            "a3_weapons_f_epb_ammoboxes",
            "a3_weapons_f_epb_longrangerifles_gm3",
            "a3_weapons_f_epb_longrangerifles_m320",
            "a3_weapons_f_epb_rifles_mx_black",
            "a3_weapons_f_epc",
            "a3_weapons_f_explosives",
            "a3_weapons_f_fia",
            "a3_weapons_f_gamma",
            "a3_weapons_f_gamma_acc",
            "a3_weapons_f_gamma_ammoboxes",
            "a3_weapons_f_gamma_items",
            "a3_weapons_f_headgear",
            "a3_weapons_f_itemholders",
            "a3_weapons_f_items",
            "a3_weapons_f_kart",
            "a3_weapons_f_kart_pistols_pistol_signal_f",
            "a3_weapons_f_launchers_law",
            "a3_weapons_f_launchers_nlaw",
            "a3_weapons_f_launchers_titan",
            "a3_weapons_f_longrangerifles_gm6",
            "a3_weapons_f_longrangerifles_m320",
            "a3_weapons_f_machineguns_m200",
            "a3_weapons_f_machineguns_zafir",
            "a3_weapons_f_mark",
            "a3_weapons_f_mark_acc",
            "a3_weapons_f_mark_ebr",
            "a3_weapons_f_mark_longrangerifles_dmr_01",
            "a3_weapons_f_mark_longrangerifles_dmr_02",
            "a3_weapons_f_mark_longrangerifles_dmr_03",
            "a3_weapons_f_mark_longrangerifles_dmr_04",
            "a3_weapons_f_mark_longrangerifles_dmr_05",
            "a3_weapons_f_mark_longrangerifles_dmr_06",
            "a3_weapons_f_mark_longrangerifles_gm6",
            "a3_weapons_f_mark_longrangerifles_gm6_camo",
            "a3_weapons_f_mark_longrangerifles_m320",
            "a3_weapons_f_mark_longrangerifles_m320_camo",
            "a3_weapons_f_mark_machineguns_m200",
            "a3_weapons_f_mark_machineguns_mmg_01",
            "a3_weapons_f_mark_machineguns_mmg_02",
            "a3_weapons_f_mark_machineguns_zafir",
            "a3_weapons_f_mark_rifles_khaybar",
            "a3_weapons_f_mark_rifles_mk20",
            "a3_weapons_f_mark_rifles_mx",
            "a3_weapons_f_mark_rifles_sdar",
            "a3_weapons_f_mark_rifles_trg20",
            "a3_weapons_f_nato",
            "a3_weapons_f_pistols_acpc2",
            "a3_weapons_f_pistols_p07",
            "a3_weapons_f_pistols_pdw2000",
            "a3_weapons_f_pistols_pistol_heavy_01",
            "a3_weapons_f_pistols_pistol_heavy_02",
            "a3_weapons_f_pistols_rook40",
            "a3_weapons_f_rifles_khaybar",
            "a3_weapons_f_rifles_mk20",
            "a3_weapons_f_rifles_mx",
            "a3_weapons_f_rifles_sdar",
            "a3_weapons_f_rifles_smg_02",
            "a3_weapons_f_rifles_trg20",
            "a3_weapons_f_rifles_vector",
            "a3_weapons_f_uniforms",
            "a3_weapons_f_vests",
            // CBA
            "extended_eventhandlers",
            "cba_ui",
            "cba_xeh",
            "cba_xeh_a3",
            "cba_jr"
        };
        author[] = {ECSTRING(main,author)};
        url = "";
        VERSION_CONFIG;
    };
};

class CfgMods {
    class PREFIX {
        dir = "@MFFA";
        name = "More Factions For Arma3 MFFA";
        picture = "A3\Ui_f\data\Logos\arma3_expansion_alpha_ca";
        hidePicture = "true";
        hideName = "true";
        description = "Issue Tracker: https://github.com/alganthe/MFFA/issues";
    };
};


class CfgSettings {
    class CBA {
        class Versioning {
            class PREFIX {
                class dependencies {
                    CBA[] = {"cba_main", REQUIRED_CBA_VERSION, "(true)"};
                };
            };
        };
    };
};
